import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Sidebar />
    </div>
  )
}

// npm install --save styled-components
// npm install @material-ui/core
// npm install @material-ui/icons
// npm install firebase
// npm install email-validator